VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Bridges"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Public Sub ThreadProcedure()
End Sub
Public Sub WaitableThreadProcedure()
End Sub
Public Function SehF(ByVal pExcept As Long, ByVal pFrame As Long, ByVal pContext As Long, ByVal pDispatch As Long) As Long
End Function
Public Function SehW(ByVal pExcept As Long, ByVal pFrame As Long, ByVal pContext As Long, ByVal pDispatch As Long) As Long
End Function


